# Generated by Django 3.2.7 on 2021-09-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
